numpy library

1D array


In [37]:
import numpy as np

list=[1,2,3,4,5]
array=np.array(list)
print(array)
print(type(array))


[1 2 3 4 5]
<class 'numpy.ndarray'>


2D array


In [38]:
import numpy as np

list=[[1,2,3], [3,4,5] ,[6,7,8]]
array1=np.array(list)
print(array1)
print(type(array1))

[[1 2 3]
 [3 4 5]
 [6 7 8]]
<class 'numpy.ndarray'>


using range

In [39]:
import numpy as np
array=np.arange(1,7)
print(array)

[1 2 3 4 5 6]


In [40]:
import numpy as np
array=np.arange(1,7).reshape(2,3)
print(array)

[[1 2 3]
 [4 5 6]]


In [41]:
import numpy as np
array=np.zeros((2,3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [42]:
import numpy as np
array=np.ones((2,3))
print(array)

[[1. 1. 1.]
 [1. 1. 1.]]


attributes in numpy


In [43]:
import numpy as np

list=[[1,2,3], [3,4,5] ,[6,7,8]]
array1=np.array(list)
print(array1)
#array1.ndim
# array1.shape
# array1.size
# array1.dtype
# array1.itemsize

[[1 2 3]
 [3 4 5]
 [6 7 8]]


indexing in numpy


In [44]:
import numpy as np
array1=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(array1)
print(array1[2,0])
print(array1[2,:])
print(array1[:,1])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
70
[70 80 90]
[20 50 80]


In [45]:
import numpy as np
array1=np.array([1,2,3,4])
print(array1[-2])
print(array1[3])

3
4


slicing in numpy

In [63]:
import numpy as np
array1=np.array([1,2,3,4,5,6,7,8])
print(array1[::-1])
print(array1[2:6])
print(array1[-1:-3:-1])


[8 7 6 5 4 3 2 1]
[3 4 5 6]
[8 7]


In [ ]:
import numpy as np
array1=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(array1[2,0])
print(array1[2,:])
print(array1[:,1])
print(array1[1:3,1:2])
print(array1[1:2,:2])


arthimetic operation 

In [61]:
import numpy  as np

x=np.array([[10,20],[30,40]])
y=np.array([[2,4],[3,4]])

z=x+y #add
z=x-y #sub
z=x/y #div
z=x//y #floor div
z=x%y #mod
z=x**y #exp
z=x*y  #mul
z=x@y  #matrix mul
print(z)
print(x.transpose())

[[ 80 120]
 [180 280]]
[[10 30]
 [20 40]]


sorting 1-D array

In [64]:
import numpy as np

x=np.array([30,20,40,10])
y=np.sort(x)
print(y)

[10 20 30 40]


In [65]:
import numpy as np

x=np.array([30,20,40,10])
y=np.argsort(x)
print(y)

[3 1 0 2]


In [66]:
import numpy as np

x=np.array([30,20,40,10])
x.sort()
print(x)

[10 20 30 40]


sorting in 2-D array

In [71]:
import numpy as np
x=np.array([[10,20,15],[40,50,25],[100,80,90]])
y=np.sort(x) #row sorting
y=np.sort(x,axis=0)#column sorting
print(y)


[[ 10  20  15]
 [ 40  50  25]
 [100  80  90]]


In [73]:
import numpy as np
x=np.array([[10,20,15],[40,50,25],[100,80,90]])
y=np.argsort(x) #row sorting
#y=np.argsort(x,axis=0)  #column sorting
print(y)

[[0 2 1]
 [2 0 1]
 [1 2 0]]


In [77]:
import numpy as np
x=np.array([[10,20,15],[40,50,25],[100,80,90]])
x.sort(axis=0) #column sorting
x.sort() 
print(x)

[[ 10  15  20]
 [ 25  40  50]
 [ 80  90 100]]


stat operations

In [82]:
import numpy as np

x=np.array([30,20,40,10])
y=np.max(x) #maximum
y=np.min(x)  #minimum
y=np.sum(x)  # sum
y=np.mean(x) # mean of array
y=np.median(x) #median 
y=np.var(x)  #variance
y=np.std(x)  #standard deviation
y=np.prod(x) #product
print(y)


240000
